apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: k5hj0eqi8-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/k5hj0eqi8-java-quarkus-gitops